/* eslint-disable */
"use client";

import { useState } from 'react';
import { Copy, CheckCircle2, RotateCw, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { exportToCSS } from '@/lib/export-utils';

type GradientType = 'linear' | 'radial';

export default function CssGradientGenerator() {
  const [color1, setColor1] = useState('#8b5cf6');
  const [color2, setColor2] = useState('#ec4899');
  const [type, setType] = useState<GradientType>('linear');
  const [angle, setAngle] = useState(135);
  const [copied, setCopied] = useState(false);
  
  const cssCode = type === 'linear' 
    ? `background: linear-gradient(${angle}deg, ${color1} 0%, ${color2} 100%);`
    : `background: radial-gradient(circle, ${color1} 0%, ${color2} 100%);`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(cssCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportCSS = () => {
    exportToCSS(`/* Generated by Warsi WebWorks */\n.custom-gradient {\n  ${cssCode}\n}`, 'gradient.css');
  };

  const randomColors = () => {
    const randomColor = () => '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0');
    setColor1(randomColor());
    setColor2(randomColor());
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      
      {/* Preview Area */}
      <div className="flex flex-col gap-4">
        <div 
          className="w-full aspect-square md:aspect-video lg:aspect-square rounded-2xl shadow-inner border border-border-section transition-all"
          style={{ 
            background: type === 'linear' 
              ? `linear-gradient(${angle}deg, ${color1} 0%, ${color2} 100%)`
              : `radial-gradient(circle, ${color1} 0%, ${color2} 100%)`
          }}
        ></div>
      </div>

      {/* Controls */}
      <div className="space-y-8">
        
        {/* Style Controls */}
        <div className="bg-surface border border-border-section p-6 rounded-xl space-y-6">
          
          <div className="flex justify-between items-center">
            <h3 className="font-bold text-text-primary">Settings</h3>
            <Button variant="outline" size="sm" onClick={randomColors} className="bg-base border-border-section">
              <RotateCw size={14} className="mr-2" /> Random
            </Button>
          </div>

          {/* Type Toggle */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-text-muted uppercase tracking-wider">Style</label>
            <div className="flex gap-2 p-1 bg-base border border-border-section rounded-lg">
              <button 
                onClick={() => setType('linear')}
                className={`flex-1 py-2 text-sm font-bold rounded-md transition-all ${type === 'linear' ? 'bg-surface shadow-sm text-text-primary' : 'text-text-muted hover:text-text-primary'}`}
              >
                Linear
              </button>
              <button 
                onClick={() => setType('radial')}
                className={`flex-1 py-2 text-sm font-bold rounded-md transition-all ${type === 'radial' ? 'bg-surface shadow-sm text-text-primary' : 'text-text-muted hover:text-text-primary'}`}
              >
                Radial
              </button>
            </div>
          </div>

          {/* Colors */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-text-muted uppercase tracking-wider">Colors</label>
            <div className="flex gap-4">
              <div className="flex-1 space-y-2">
                <div 
                  className="w-full h-12 rounded-lg border-2 border-border-section relative overflow-hidden"
                  style={{ backgroundColor: color1 }}
                >
                  <input 
                    type="color" 
                    value={color1} 
                    onChange={e => setColor1(e.target.value)}
                    className="absolute inset-[-10px] w-[calc(100%+20px)] h-[calc(100%+20px)] opacity-0 cursor-pointer"
                  />
                </div>
                <div className="text-center font-mono text-sm">{color1.toUpperCase()}</div>
              </div>
              
              <div className="flex-1 space-y-2">
                <div 
                  className="w-full h-12 rounded-lg border-2 border-border-section relative overflow-hidden"
                  style={{ backgroundColor: color2 }}
                >
                  <input 
                    type="color" 
                    value={color2} 
                    onChange={e => setColor2(e.target.value)}
                    className="absolute inset-[-10px] w-[calc(100%+20px)] h-[calc(100%+20px)] opacity-0 cursor-pointer"
                  />
                </div>
                <div className="text-center font-mono text-sm">{color2.toUpperCase()}</div>
              </div>
            </div>
          </div>

          {/* Angle (Only for Linear) */}
          {type === 'linear' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center text-sm">
                <label className="font-medium text-text-muted uppercase tracking-wider">Angle</label>
                <span className="font-mono bg-base px-2 py-1 rounded">{angle}°</span>
              </div>
              <input 
                type="range" 
                min="0" max="360" 
                value={angle}
                onChange={e => setAngle(Number(e.target.value))}
                className="w-full accent-accent"
              />
            </div>
          )}

        </div>

        {/* Output Code */}
        <div className="space-y-3">
          <label className="text-sm font-bold text-text-primary">CSS Code</label>
          <div className="relative">
            <pre className="p-4 bg-[#1e1e1e] border border-border-section rounded-xl text-sm font-mono text-[#d4d4d4] overflow-x-auto">
              <code>{cssCode}</code>
            </pre>
            <div className="absolute top-3 right-3 flex gap-2">
              <Button 
                size="sm" 
                onClick={copyToClipboard}
                className={copied ? 'bg-emerald-500 hover:bg-emerald-600 text-white' : 'bg-surface/20 text-white hover:bg-surface/40'}
              >
                {copied ? <><CheckCircle2 size={14} className="mr-2" /> Copied</> : <><Copy size={14} className="mr-2" /> Copy CSS</>}
              </Button>
              <Button 
                size="sm" 
                onClick={handleExportCSS}
                className="bg-accent hover:bg-accent-hover text-white"
              >
                <Download size={14} className="mr-2" /> Download
              </Button>
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}

